AWSTemplateFormatVersion: '2010-09-09'
Description: >
  API Gateway + Lambda proxy for SageMaker vLLM endpoint.
  Exposes an OpenAI-compatible API without authentication.

Parameters:
  SageMakerEndpointName:
    Type: String
    Description: Name of the SageMaker endpoint to proxy requests to
    Default: vllm-endpoint-20260122-074720

  LambdaFunctionName:
    Type: String
    Description: Name for the Lambda function
    Default: sagemaker-openai-proxy

Resources:
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${LambdaFunctionName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SageMakerInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/${SageMakerEndpointName}'

  # Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT_NAME: !Ref SageMakerEndpointName
          AWS_REGION_NAME: !Ref AWS::Region
      Code:
        ZipFile: |
          # Placeholder - deploy actual code separately
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy code separately'}

  # HTTP API Gateway (simpler and cheaper than REST API)
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${LambdaFunctionName}-api'
      ProtocolType: HTTP
      Description: OpenAI-compatible API for SageMaker vLLM endpoint
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization

  # API Gateway Stage
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  # Lambda Integration
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt LambdaFunction.Arn
      PayloadFormatVersion: '2.0'

  # Route: POST /v1/chat/completions
  ChatCompletionsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /v1/chat/completions'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Route: POST /v1/completions
  CompletionsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'POST /v1/completions'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Route: GET /v1/models
  ModelsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /v1/models'
      Target: !Sub 'integrations/${LambdaIntegration}'

  # Permission for API Gateway to invoke Lambda
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*'

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt HttpApi.ApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'

  LambdaFunctionName:
    Description: Lambda function name (for code deployment)
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaName'

  ExampleCurlCommand:
    Description: Example curl command to test the API
    Value: !Sub |
      curl -X POST ${HttpApi.ApiEndpoint}/v1/chat/completions \
        -H "Content-Type: application/json" \
        -d '{"messages": [{"role": "user", "content": "The future of AI is"}], "max_tokens": 50}'
